<?php
namespace App\Command;

use Cake\Datasource\ConnectionManager;
use Cake\Filesystem\File;
use Symfony\Component\Process\Process;
use Cake\Console\Arguments;
use Cake\Console\Command;
use Cake\Console\ConsoleIo;
use Cake\Console\ConsoleOptionParser;
use Cake\I18n\Time;

/**
 * BackupDatabase command.
 * This SQL script generation code is taken from Camelot IE Demonstration System, developed by Faculty of IT, Monash University
 */
class DatabaseBackupCommand extends Command
{

    protected function buildOptionParser(ConsoleOptionParser $parser)
    {
        $parser->setDescription('This command creates a backup sql file into config/schema');
        return $parser;
    }

    public function execute(Arguments $args, ConsoleIo $io)
    {
        $connection = ConnectionManager::get('default');
        $config = $connection->config();
        $db = $config['database'];
        $dateTime = Time::now();
        ;
        $filePath = BACKUP_SCHEMA_DIR .
            $config['file_prefix'] . DOT .
            $dateTime->format($config['file_timestamp_format']) . DOT .
            $config['file_type'];
        $scriptFile = new File($filePath);

        $process = new Process([
            'mysqldump',
            "--user={$config['username']}",
            "--password={$config['password']}",
            "--host={$config['host']}",
            '--add-drop-table',
            $db,
        ]);
        $io->out('Creating a backup sql file');
        $process->run();
        $dumpedData = $process->getOutput();
        if ($process->getExitCode() !== 0) {
            $io->error("Error dumping tables");
            $error = $process->getErrorOutput();
            if ($error) {
                $io->error($error);
            }

            return false;
        } elseif (!trim($dumpedData)) {
            $io->error("mysqldump completed but returned no data");

            return false;
        }

        $newSqlScript = <<<SQL
-- =========================================================================================
--   This file is automatically generated by the "bin/cake database_backup" command.
-- =========================================================================================

-- -----------------------------------------------------------------------------------------
-- Output from "mysqldump --add-drop-table" Version: 0.5 16/02/2019
-- -----------------------------------------------------------------------------------------

$dumpedData
SQL;
        $io->verbose($newSqlScript);
        $scriptFile->write($newSqlScript);
        $io->success("Wrote " . strlen($newSqlScript) . " bytes of output to " );
        $io->success($filePath);
        $io->out('Done!');

        return true;
    }
}
