<?php
/**
 * Created by PhpStorm.
 * User: weng
 * Date: 31/10/2018
 * Time: 00:07
 */

namespace App\Command;

use Cake\Console\Arguments;
use Cake\Console\Command;
use Cake\Console\ConsoleIo;

class HelloCommand extends Command{
    public function execute(Arguments $args, ConsoleIo $io)
    {

        $io->out('Hello World');
//        return parent::execute($args, $io); // TODO: Change the autogenerated stub
    }
}